### PR TITLE
Search for libneo4j-client by architecture on Linux

### PR DESCRIPTION
**Pull request by johannessen**
Addresses #28.

However, I guess there may be many other locations the library may have been installed into. Not sure what the best way would be to find them all.

### CODE REVIEW

**Comment by johannessen** [comment]
Hmm, looks like [Devel::CheckLib](https://metacpan.org/pod/Devel::CheckLib) might offer a better solution.

**Comment by majensen** [comment]
The question as to write tests is relevant, because a user may want to allow only reads. I would put it back in.

**Comment by majensen** [comment]
Devel::CheckLib probably does everything that Build.PL is doing by hand, may want to refactor to use it.

**Comment by johannessen** [comment]
Right. I didn’t realise before that Devel::CheckLib only gives a “yes or no” answer. I somehow thought it might also give the location of the library, but I see now that’s not the case.

The question about write tests *is* still in with this change. It’s just being suppressed when the user didn’t supply any access credentials for read tests.

(My commit message was badly worded. Sorry about that.)

**Comment by majensen** [comment]
Ah! I get it. 
Hmm - I can play with looking for libs. Should be "easier" on linux, since the *nixes actually have package management!

**Comment by majensen** [comment]
Ok, we'll merge this, release 0.13 and see if Slaven's smokers work.

**Pull request merged**
